//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pasikonik.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Pasikonik.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wygral komputer.
        /// </summary>
        internal static string COMPUTER_WIN {
            get {
                return ResourceManager.GetString("COMPUTER_WIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wygral komputer. Znaleziono wzorzec :.
        /// </summary>
        internal static string FOUND_PATTERN {
            get {
                return ResourceManager.GetString("FOUND_PATTERN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poddaje sie.
        /// </summary>
        internal static string GAME_END {
            get {
                return ResourceManager.GetString("GAME_END", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start gry.
        /// </summary>
        internal static string Game_START {
            get {
                return ResourceManager.GetString("Game_START", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon grasshopper {
            get {
                object obj = ResourceManager.GetObject("grasshopper", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Woohooo! Wygrales .
        /// </summary>
        internal static string PLAYER_WIN {
            get {
                return ResourceManager.GetString("PLAYER_WIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * Komputer wstawia wybrana litere lub dwie na koniec slowa ( w zaleznosci od pozycji pasikonika ) ,
        ///* Ty jako pasikonik mozesz skoczyc na sasiednia litere albo przeskoczyc jedna litere ( pasikonik nie moze sie cofac ),
        ///* Litery, na ktorych wyladuje pasikonik tworza slowo S,
        ///* Komputer  wygrywa, gdy w slowie S wystapi wzorzec,
        ///* Ty wygrywasz, gdy slowo S osiagnie zadana dlugosc, a wzorzec sie nie pojawi,
        ///* Liczba liter wstawianych przez komputer  zalezy od tego, gdzie znajduje sie pasikonik.
        ///  Jezeli j [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string rules {
            get {
                return ResourceManager.GetString("rules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Niewlasciwy ruch pasikonika.
        /// </summary>
        internal static string ValidateMove_Niewlasciwy_ruch_pasikonika {
            get {
                return ResourceManager.GetString("ValidateMove_Niewlasciwy_ruch_pasikonika", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR.
        /// </summary>
        internal static string Validator__ERROR {
            get {
                return ResourceManager.GetString("Validator__ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zwyciezca.
        /// </summary>
        internal static string WINNER {
            get {
                return ResourceManager.GetString("WINNER", resourceCulture);
            }
        }
    }
}
